crypal/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        # TemplateView.as_view(template_name='pages/home.html'),
        'users.views.home',
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crypal/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

crypal/users/models.py
# -*- coding: utf-8 -*-
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser

# Import the basic Django ORM models library
from django.db import models

from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save

from allauth.socialaccount.models import SocialAccount
import hashlib

from django.core import mail


# Subclass AbstractUser
class User(AbstractUser):

    def __unicode__(self):
        return self.username


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    public_key = models.CharField(max_length=100, null=True,\
     blank=True)
    write_about = models.TextField(null=True, blank=True)
    list_user = models.BooleanField(default=True)

    
    def __unicode__(self):
        return "{}'s profile".format(self.user.username)
 
    class Meta:
        db_table = 'user_profile'

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        mail.mail_admins('New cryptopals user', 'New user')

post_save.connect(create_user_profile, sender=User)


# User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

crypal/users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import Textarea

from .models import User, UserProfile


class UserForm(forms.ModelForm):
    first_name = forms.CharField(label="Name", max_length=30)
    last_name = forms.CharField(label="Surname", max_length=30)

    def __init__(self, *args, **kw):
        super(UserForm, self).__init__(*args, **kw)
        self.fields['first_name'].initial = self.instance.first_name
        self.fields['last_name'].initial = self.instance.last_name
        self.fields['public_key'].initial = self.instance.profile.public_key
        self.fields['list_user'].initial = self.instance.profile.list_user
        self.fields['write_about'].initial = self.instance.profile.write_about

        self.fields.keyOrder = [
            'first_name',
            'last_name',
            'public_key',
            'list_user',
            'write_about'
            ]

    def save(self, *args, **kw):
        super(UserForm, self).save(*args, **kw)
        self.instance.first_name = self.cleaned_data.get('first_name')
        self.instance.last_name = self.cleaned_data.get('last_name')
        profile = self.instance.profile
        profile.public_key = self.cleaned_data.get('public_key')
        profile.write_about = self.cleaned_data.get('write_about')
        profile.list_user = self.cleaned_data.get('list_user')
        profile.save()
        self.instance.save()

    class Meta:
        model = UserProfile
        labels = {
            'public_key': ('Public Key ID'),
            'write_about': ('What I write about as a penpal. More detail the better.'),
            'list_user': ('List your profile on the site? \
                You can add yourself again at any time.')
        }
        # widgets = {
        #     'write_about': Textarea(attrs={'label':'What I write about as a penpal'}),
        # }

crypal/users/views.py
# -*- coding: utf-8 -*-
# Import the reverse lookup function
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.template import RequestContext

# view imports
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django.views.generic import ListView

# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin

# Import the form from users/forms.py
from .forms import UserForm

# Import the customized User model
from .models import User, UserProfile

def home(request):
    pals = UserProfile.objects.filter(list_user=True)
    context = RequestContext(request)
    context['pals'] = pals
    return render_to_response('pages/home.html', context)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
            kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                    kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

crypal/templates/avatar/add.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

crypal/templates/avatar/avatar_tag.html
<img src="{{ url }}" width="{{ size }}" height="{{ size }}" class="img-thumbnail">

crypal/templates/avatar/base.html
{% extends "base.html" %}

{% block content %}{% endblock %}

crypal/templates/avatar/change.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% else %}
            <form method="POST" action="{% url 'avatar_change' %}">
                <ul>
                    {{ primary_avatar_form.as_ul }}
                </ul>
                <p>{% csrf_token %}<input type="submit" value="{% trans "Choose new Default" %}" /></p>
            </form>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

crypal/templates/avatar/confirm_delete.html
{% extends "avatar/base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
    <h2>{% trans "Please select the avatars that you would like to delete." %}</h2>
    {% if not avatars %}
        {% url 'avatar_change' as avatar_change_url %}
        <p>{% blocktrans %}You have no avatars to delete. Please <a href="{{ avatar_change_url }}">upload one</a> now.{% endblocktrans %}</p>
    {% else %}
        <form method="POST" action="{% url 'avatar_delete' %}">
            <ul>
                {{ delete_avatar_form.as_ul }}
            </ul>
            <p>{% csrf_token %}<input type="submit" value="{% trans "Delete These" %}" /></p>
        </form>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

crypal/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}cryptopals{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Get an encrypted email penpal">
    <meta name="author" content="">


    <meta property="og:title" content="cryptopals" />
    <meta property="og:site_name" content="Cryptopals Get an encrypted email penpal" />
    <meta property="og:url" content="http://www.cryptopals.org" />
    <meta property="og:image" content="https://s3-eu-west-1.amazonaws.com/cryptopal/images/cryptopal.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:width" content="64" />
    <meta property="og:image:height" content="63" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Get an encrypted email penpal" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" type="image/png" href="https://s3-eu-west-1.amazonaws.com/cryptopal/images/cryptopal.png" />

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-docs.css' %}" type="text/css" media="screen">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

    <!-- Your stuff: Third-party css libraries go here -->
    <link href="{% static 'css/socialite.css' %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Rosarivo' rel='stylesheet' type='text/css'>

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <div class="header navbar">
      <div class="container">
        <ul class="nav navbar-nav">
<!--           <li class="active"><a href="{% url 'home' %}">Home</a></li> -->
          <li class="active"><a href="/"><img src="https://s3-eu-west-1.amazonaws.com/cryptopal/images/cryptopal.png" style="width: 20px; height: 20px;">  <strong>cryptopals</strong></a></li>
          <li><a href="{% url 'about' %}">About</a></li>

          {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
            <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="container">
        
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}

      {% endblock content %}

    </div> <!-- /container -->
    
    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
      <script src="{% static 'js/socialite.min.js' %}"></script>

      <script>
      $(document).ready(function(){
          Socialite.load()
      });
      </script>
        
      <script>
      $(document).ready(function(){
          $(".tooltip").tooltip()

      });
      </script>

      <script type="text/javascript">
        /* <![CDATA[ */
        (function() {
            var s = document.createElement('script');
            var t = document.getElementsByTagName('script')[0];

            s.type = 'text/javascript';
            s.async = true;
            s.src = '//api.flattr.com/js/0.6/load.js?mode=auto';

            t.parentNode.insertBefore(s, t);
         })();
        /* ]]> */
      </script>

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48024231-1', 'cryptopals.org');
  ga('send', 'pageview');

</script>
  </body>
</html>
 

crypal/templates/pages/about.html
{% extends "base.html" %}

{% block content %}


<h4>How does it work?</h4>

<div class="about">

<p><img src="https://cryptopal.s3.amazonaws.com/images/postie.jpg" class="image-vertical small-width">Find a new pal's contact email and public key ID. In return, offer your own for someone else.</p>

<p>Then just email them to practice your encryption skills whilst getting to know someone else who cares about digital self-defense.</p>

</div>

<h4>What is my Key ID?<a name="KeyID">&nbsp;</a></h4>

<div class="about">

<p>Your public key is quite long so it's useful to have a shorthand to reference it. The Key ID is one such reference. You can use your Key ID to search for your details on public keyservers, such as the <a href="http://pgp.mit.edu/">MIT Public Key server</a>. These keyservers are a good place to publically list your key so that anyone can encrypt mail to you if they have your email address or Key ID.</p>

<p>Here is an example of the Key ID format: <strong>0xaadf931610a62df8</strong></p>

</div>

<h4>Under construction</h4>

<div class="about">

<p>This site is under active development. It went live in February 2014 and will see major improvements in the coming months. Please let us know if <a href="mailto:info@cryptopals.org">you can help, have questions or notice that a listed cryptopal is non-responsive</a>.</p>

</div>

<h4>Support this project</h4>

<div class="about">

<p>We hope to improve and expand this site as a community resource for email encryption. Please share with your networks and support the project.</p>

  <div id="shares">
  	<p>
	    <ul id="social">
	        <li><a href="http://twitter.com/share" class="socialite twitter-share" data-text="Get a pen pal to share encrypted email with" data-url="http://www.cryptopals.org" data-count="vertical" rel="nofollow" target="_blank"><span class="vhidden">Share on Twitter</span></a></li>
	        <li><a href="https://plus.google.com/share?url=http://www.cryptopals.org" class="socialite googleplus-one" data-size="tall" data-href="http://www.cryptopals.org" rel="nofollow" target="_blank"><span class="vhidden">Share on Google+</span></a></li>
	        <li><a href="http://www.facebook.com/sharer.php?u=http://www.cryptopals.org&amp;t=Get%20a%20pen%20pal%20to%20share%20encrypted%20email%20with%20at%20www.cryptopals.org" class="socialite facebook-like" data-href="http://www.cryptopals.org" data-send="false" data-layout="box_count" data-width="60" data-show-faces="false" rel="nofollow" target="_blank"><span class="vhidden">Share on Facebook</span></a></li>
<!-- 	        <li><a class="FlattrButton" style="display:none;" title="Find a friendly, encrypted email penpal." data-flattr-uid="Mattguy" data-flattr-tags="communities, encryption, Snowden" data-flattr-category="text" href="http://www.cryptopals.org"><img src="https://api.flattr.com/button/flattr-badge-large.png" alt="Flattr this" title="Flattr this" border="0" /></a></li> -->
	    </ul>
	</p>
  </div>
  <br /><br /><br /><br />

<p><a href="bitcoin:1AvQwcMqNXGRZbHYhxMa3DgZ3Ce9rdLx3V?label=Donation">Donate with bitcoin&rarr;</a></p>

<p><a href="mailto:info@cryptopals.org">Please let us know</a> of other offers of support, particularly publicity, web hosting and development.</p>

</div>

<h4>Is encryption worth it?</h4>

<div class="about" id="encryption-worth-it">

<p>People may say that small-scale efforts, such as cryptopals.org, to encourage and assist encryption uptake are insignificant compared to the amount of uptake necessary.</p>

<p>Some say that we need slicker, convenient email encryption provision from big companies to achieve real privacy in society. Such an outcome, if brought about with honest, credible technical implementation, would be ideal.</p>

<div class="image-horizontal caption small-width"><img src="https://cryptopal.s3.amazonaws.com/images/email-data-ads-biz.png" class="full-width"><div class="caption">The marketing value of your data is seen in the ads that surround your emails.</div></div>

<p>That ideal would incorporate <a href="http://darkmail.info/">true end-to-end, user-to-user email encryption</a>, not merely a secure connection to, from and between data centres.</p>

<p>But it would also, probably, rely on those companies sacrificing a chief element of their business model, that is, the ability to mine user email data, content and all, for its marketing value.</p>

<p>Even if it were to happen, it would likely be thanks to demand. That demand will grow as people are helped to increase their use of encryption. The more ordinary folks encrypt, the greater demand will be.</p>

<p>So, tools which help people upskill together help support a positive transition.</p>

</div>

{% endblock %}

crypal/templates/pages/home.html
{% extends "base.html" %}

      {% block content %}
      {% load avatar_tags %}

      <div class="container" id="intro">

      <h3>Get an encrypted email buddy</h3>

      <div class="about">
      <p><img src="https://cryptopal.s3.amazonaws.com/images/letter.jpg" class="image-horizontal large-width">More people than ever want to communicate privately, without creeps collecting their info. Encrypting your email is part of the solution. <a href="http://lifehacker.com/180878/how-to-encrypt-your-email">It's not hard, learn how&rarr;</a></p>

      <p>But not everyone has someone to share encrypted email with. Find a friendly cryptopal right here.</p>

      <p>Discover someone who interests you from our list, get their email and public key (<a href="http://www.comodo.com/resources/small-business/digital-certificates2.php">what's that?</a>) by clicking on their Key ID, and send a greeting. Or <a href="/accounts/signup">offer yourself as a buddy to meet others encrypting</a>.</p>
      </div>

      <h3>Why?</h3>

      <div class="about">
      <p>To practice critical skills for private data. To regain the romance of sacred communications and meet new people who care about online privacy.</p>
      </div>

      <h3>Support the project</h3>
      
      <div class="about">
      <p>Share this with your networks and support the project.</p>


          <div id="shares">
            <ul id="social">
                <li><a href="http://twitter.com/share" class="socialite twitter-share" data-text="Get a pen pal to share encrypted email with" data-url="http://www.cryptopals.org" data-count="vertical" rel="nofollow" target="_blank"><span class="vhidden">Share on Twitter</span></a></li>
                <li><a href="https://plus.google.com/share?url=http://www.cryptopals.org" class="socialite googleplus-one" data-size="tall" data-href="http://www.cryptopals.org" rel="nofollow" target="_blank"><span class="vhidden">Share on Google+</span></a></li>
                <li><a href="http://www.facebook.com/sharer.php?u=http://www.cryptopals.org&amp;t=Get%20a%20pen%20pal%20to%20share%20encrypted%20email%20with%20at%20www.cryptopals.org" class="socialite facebook-like" data-href="http://www.cryptopals.org" data-send="false" data-layout="box_count" data-width="60" data-show-faces="false" rel="nofollow" target="_blank"><span class="vhidden">Share on Facebook</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      
      {% load shuffle %}
      <div id="pals" class="js-masonry" data-masonry-options='{ "itemSelector": ".pal" }'>
            <div class="row">
            {% for pal in pals|shuffle %}
                  <div class="pal col-6 col-sm-6 col-lg-4">



                        <img src="{% avatar_url pal.user %}" class="pal-pic">
                        <div class="name-key"><p class="username"><strong>{{ pal.user.username }}</strong></p><strong>Key ID </strong><a href="/about#KeyID"><span class="tooltip" data-toggle="tooltip" title="Public keys are long. It's good to have a shorthand, like the Key ID. You can use them to search for email addresses on public keyservers. It's good to list your key on keyservers so anyone can encrypt mail to you.">(?)</span></a><br />
                        <a href="http://pgp.mit.edu/pks/lookup?op=get&search={% if pal.public_key %}{{ pal.public_key }}{% else %}{{ pal.user.email }}{% endif %}&op=index"><span class="smaller-text">{% if pal.public_key %}{{ pal.public_key }}{% else %}{{ pal.user.email }}{% endif %}</span></a></div>
                        {% if pal.write_about %}
                        <div class="write-to-me-about" class="write-about">
                        <p><strong>Write to me about...</strong></p>
                        <p class="small-text">{{ pal.write_about }}</p>
                        </div>
                        {% endif %}

                  </div>
            {% endfor %}
      </div>
      </div>

      {% endblock content %}

crypal/templates/users/user_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->     
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <a class="btn btn-info" href="{% url 'avatar_change' %}">Avatar</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

crypal/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}User: {{ user.username }}{% endblock %}</h1>
            <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Update</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

crypal/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% load avatar_tags %}

{% block title %}Members{% endblock %}

{% block content %}

<div class="container">
    
  <div class="row">
    <div class="col-xs-12">
      <h2>Users</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="list-group">
          {% for user in user_list %}
            <a href="{% url 'users:detail' user.username %}" class="list-group-item">
              <h4 class="list-group-item-heading">{% avatar user %} {{ user.username }}</h4>
              <p class="list-group-item-text">{{ maker.tagline }}</p>
            </a>
          {% endfor %}
        
      </div>
    </div>
  </div>

</div>

{% endblock content %}